### ISSUE TITLE
Inline code font is too large on mobile

### ISSUE THREAD

**Issue by gaearon** [gaearon/overreacted.io#20]
On iPhone safari `inline code` font is too large compared to surrounding text. Need to bump down. But for desktop we should keep current size.

**Comment by alexeyraspopov** [comment]
It's happening due to text size adjust mechanism: https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust

Can be fixed by

```css
body {
  -webkit-text-size-adjust: 100%;
}
```
